// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRepository(arg1:string):Promise<main.Repository>;

export function CheckoutBranch(arg1:string,arg2:string):Promise<void>;

export function Commit(arg1:string,arg2:string):Promise<void>;

export function CreateBranch(arg1:string,arg2:string):Promise<void>;

export function Fetch(arg1:string):Promise<void>;

export function GetBranches(arg1:string):Promise<Array<main.Branch>>;

export function GetCommitDiff(arg1:string,arg2:string,arg3:string):Promise<main.DiffResult>;

export function GetCommitFiles(arg1:string,arg2:string):Promise<Array<main.FileStatus>>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetDiff(arg1:string,arg2:string,arg3:boolean):Promise<main.DiffResult>;

export function GetLog(arg1:string,arg2:number):Promise<Array<main.CommitInfo>>;

export function GetRepoInfo(arg1:string):Promise<Record<string, string>>;

export function GetStatus(arg1:string):Promise<Array<main.FileStatus>>;

export function GetUntrackedDiff(arg1:string,arg2:string):Promise<main.DiffResult>;

export function LoadRepositories():Promise<Array<main.Repository>>;

export function OpenFolderDialog():Promise<string>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OpenInTerminal(arg1:string):Promise<void>;

export function Pull(arg1:string):Promise<void>;

export function Push(arg1:string):Promise<void>;

export function RemoveRepository(arg1:string):Promise<void>;

export function SaveRepositories(arg1:Array<main.Repository>):Promise<void>;

export function StageAll(arg1:string):Promise<void>;

export function StageFile(arg1:string,arg2:string):Promise<void>;

export function UnstageAll(arg1:string):Promise<void>;

export function UnstageFile(arg1:string,arg2:string):Promise<void>;
