// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepository(arg1) {
  return window['go']['main']['App']['AddRepository'](arg1);
}

export function CheckoutBranch(arg1, arg2) {
  return window['go']['main']['App']['CheckoutBranch'](arg1, arg2);
}

export function Commit(arg1, arg2) {
  return window['go']['main']['App']['Commit'](arg1, arg2);
}

export function CreateBranch(arg1, arg2) {
  return window['go']['main']['App']['CreateBranch'](arg1, arg2);
}

export function Fetch(arg1) {
  return window['go']['main']['App']['Fetch'](arg1);
}

export function GetBranches(arg1) {
  return window['go']['main']['App']['GetBranches'](arg1);
}

export function GetCommitDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCommitDiff'](arg1, arg2, arg3);
}

export function GetCommitFiles(arg1, arg2) {
  return window['go']['main']['App']['GetCommitFiles'](arg1, arg2);
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['App']['GetCurrentBranch'](arg1);
}

export function GetDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDiff'](arg1, arg2, arg3);
}

export function GetLog(arg1, arg2) {
  return window['go']['main']['App']['GetLog'](arg1, arg2);
}

export function GetRemotes(arg1) {
  return window['go']['main']['App']['GetRemotes'](arg1);
}

export function GetRepoInfo(arg1) {
  return window['go']['main']['App']['GetRepoInfo'](arg1);
}

export function GetStatus(arg1) {
  return window['go']['main']['App']['GetStatus'](arg1);
}

export function GetUntrackedDiff(arg1, arg2) {
  return window['go']['main']['App']['GetUntrackedDiff'](arg1, arg2);
}

export function LoadPreferences() {
  return window['go']['main']['App']['LoadPreferences']();
}

export function LoadRepositories() {
  return window['go']['main']['App']['LoadRepositories']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function OpenInTerminal(arg1) {
  return window['go']['main']['App']['OpenInTerminal'](arg1);
}

export function Pull(arg1, arg2, arg3) {
  return window['go']['main']['App']['Pull'](arg1, arg2, arg3);
}

export function PullWithStrategy(arg1, arg2) {
  return window['go']['main']['App']['PullWithStrategy'](arg1, arg2);
}

export function Push(arg1) {
  return window['go']['main']['App']['Push'](arg1);
}

export function PushToRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['PushToRemote'](arg1, arg2, arg3);
}

export function RemoveRepository(arg1) {
  return window['go']['main']['App']['RemoveRepository'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function SaveRepositories(arg1) {
  return window['go']['main']['App']['SaveRepositories'](arg1);
}

export function SetRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRemote'](arg1, arg2, arg3);
}

export function StageAll(arg1) {
  return window['go']['main']['App']['StageAll'](arg1);
}

export function StageFile(arg1, arg2) {
  return window['go']['main']['App']['StageFile'](arg1, arg2);
}

export function UnstageAll(arg1) {
  return window['go']['main']['App']['UnstageAll'](arg1);
}

export function UnstageFile(arg1, arg2) {
  return window['go']['main']['App']['UnstageFile'](arg1, arg2);
}
